### ISSUE TITLE
Critiques on your concept

### ISSUE THREAD

**Issue by shiva007oct** [deco3500/DJMZ#1]
- What did you mean by ‘visual location’? 
- The concept sounds very similar to google maps
- Like the aspect of crowdsourcing information
- The technology aspect is covered pretty well
- where is the aspect of feedback and motivation?
- The functions to this hasn’t been elaborated clearly
- Curation could be a part of the process
- Categorisation could be a part of the idea. 
  _\- Overall, a decent concept. Good Job!_

**Comment by zzjrzz** [comment]
- Visual location would be a graphical representation of the location as well as the various news items around them
- Yes but google maps does not allow submissions of certain news items by multiple people
- We allow people to rate news items so that will be a factor to determining if the news item is real
- We have considered categorization but decided we didn't want to introduce limitations for the user
